# Generated by Django 4.0.4 on 2022-05-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Nacional', 'Nacional'), ('Ingrediente', 'Ingrediente')], max_length=50),
        ),
    ]
