# Generated by Django 4.0.4 on 2022-05-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], max_length=50),
        ),
    ]
